### ISSUE TITLE
different outputs in R from your code

### ISSUE THREAD

**Issue by miladgha** [jhli973/Incubator#1]
Hi, I really like your analysis and tried to do what you did with R, but I noticed some different results.  Your code indicates that the 1029th ( which is " ==)!)(=\r\n><script>alert(1)</script> " ) password has the biggest length with 35 character, But my code in R shows that the biggest length is from password number 1694 which has the length of 29 characters. I checked the text file and found out that your code somehow mixed passwords number 1038( 8 characters) & 1039 (27 characters) together as password number 1029.

**Comment by jhli973** [comment]
@miladgha , Thank you for pointing out. I have fixed this issue. Have you completed this project by R? I look forward to reading it.

**Comment by miladgha** [comment]
I'm halfway through it and it's actually just what you did with Python in R with some slight differences, I will upload my codes on github and notify you when I'm done.

**Comment by jhli973** [comment]
Great! I would like to do a R version also but just don't have time. Hope you will complete it soon.!
